### ISSUE TITLE
Attempting to Go to Another Room fails

### ISSUE THREAD

**Issue by N-Roberts** [LiferayChicagoPod/great-lakes-support#63]
Please enter a number from the following choices: 
1: Inspect the room
2: Inspect the items you are carrying
3: Go to another room
3

You see doors leading to:
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at mercury.core.rooms.BasicRoom.printDoors(BasicRoom.java:80)
	at mercury.core.levels.BasicLevel.makeDecision(BasicLevel.java:146)
	at mercury.levels.levelOne.LevelOne.startLevel(LevelOne.java:105)
	at mercury.core.MercuryGame.startGame(MercuryGame.java:22)
	at main.GameSelector.main(GameSelector.java:40)

Process finished with exit code 1

**Comment by brianlarson733** [comment]
I'll work on this.

**Comment by brianlarson733** [comment]
Fixed on https://github.com/LiferayChicagoPod/great-lakes-support/pull/64
